testkube-api:
  uiIngress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"
    path: /results/(v\d/.*)
    hosts:
      - testkube-api.com
    tlsenabled: "false"
#    tls:
#      - hosts:
#          - testkube-api.com
#        secretName: testkube-cert-secret


testkube-dashboard:
  ingress:
    enabled: "true"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      acme.cert-manager.io/http01-edit-in-place: "true"
    path: /
    hosts:
      - testkube-dashboard.com
    tlsenabled: "false"
#    tls:
#      - hosts:
#          - testkube-dashboard.com
#        secretName: testkube-cert-secret

  apiServerEndpoint: "testkube-api.com/results"
